import Cloud from './Cloud';
import FadeCloud from './FadeCloud';

function Fumes() {
  return (
    <div>
      <Cloud
        top={135}
        scale={9}
        left={50}
        z={2}
      ></Cloud>
      <Cloud
        top={120}
        scale={6}
        left={36}
        z={2}
      ></Cloud>
      <Cloud
        top={85}
        scale={3}
        left={47.4}
        z={1}
      ></Cloud>
      <Cloud
        top={115}
        scale={7}
        left={87.1}
        z={2}
      ></Cloud>
      <Cloud
        top={125}
        scale={7}
        left={67.1}
        z={2}
      ></Cloud>
      <Cloud
        top={95}
        scale={3}
        left={31}
        z={1}
      ></Cloud>
      <Cloud
        top={95}
        scale={4}
        left={15}
        z={1}
      ></Cloud>
      <Cloud
        top={95}
        scale={8}
        left={-10}
        z={1}
      ></Cloud>
      <Cloud
        top={88}
        scale={4}
        left={5}
        z={1}
      ></Cloud>
      <Cloud
        top={100}
        scale={4}
        left={25}
        z={1}
      ></Cloud>
      <Cloud
        top={110}
        scale={6}
        left={40}
        z={1}
      ></Cloud>
      <Cloud
        top={115}
        scale={6}
        left={20}
        z={1}
      ></Cloud>
      <Cloud
        top={115}
        scale={9}
        left={-5}
        z={1}
      ></Cloud>
      <Cloud
        top={115}
        scale={7}
        left={55}
        z={1}
      ></Cloud>
      <Cloud
        top={90}
        scale={5}
        left={90}
        z={1}
      ></Cloud>
      <Cloud
        top={110}
        scale={6}
        left={65}
        z={1}
      ></Cloud>
      <Cloud
        top={105}
        scale={6}
        left={80}
        z={1}
      ></Cloud>
      <Cloud
        top={100}
        scale={10}
        left={110}
        z={1}
      ></Cloud>
      
    </div>
  );
}

export default Fumes;
